some updates
tocdb: use more templates in DB class instead of String
tocdb: make DBDriver and AbstractQueryBuilder noncopyable
tocdb: add CantCloseDBException
tocexception: CoreException message output contains name of Exception class
tocexception: add String getMessage() to CoreException so we can work with a String class
tocdb: add SQLite Driver (not finished)
tocdb: make MySQLQueryBuilder::StartTransaction, MySQLQueryBuilder::CommitTransaction and MySQLQueryBuilder::RollbackTransaction to member only methods
test: add tocexception test cases